server:
  port: "8080"
  read_timeout: "15s"
  write_timeout: "15s"
  idle_timeout: "60s"

auth:
  jwt_secret: "${JWT_SECRET}" # Must be set via environment variable
  token_duration: "24h"
  bcrypt_cost: 12
  session_timeout: "24h"

logging:
  level: "warn"
  format: "json"
